[versions]
agp = "8.13.1"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"
recyclerviewV7 = "28.0.0"
cardviewV7 = "28.0.0"
design = "28.0.0"
recyclerview = "1.4.0"
materialVersion = "1.13.0-rc01"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
recyclerview-v7 = { group = "com.android.support", name = "recyclerview-v7", version.ref = "recyclerviewV7" }
cardview-v7 = { group = "com.android.support", name = "cardview-v7", version.ref = "cardviewV7" }
design = { group = "com.android.support", name = "design", version.ref = "design" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "materialVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

